//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoctorOfficeManagementEntities : DbContext
    {
        public DoctorOfficeManagementEntities()
            : base("name=DoctorOfficeManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<DigitalFile> DigitalFiles { get; set; }
        public virtual DbSet<DoctorTask> DoctorTasks { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<ImagesOfFile> ImagesOfFiles { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<VisitPrice> VisitPrices { get; set; }
        public virtual DbSet<Visit> Visits { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Revenues> Revenueses { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserAction> UserActions { get; set; }
    }
}
